id: P562C2A5A
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: it
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    1a53c2332bcb41819c4cb79be76d80ba:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    f77992eb3f3f436e954398ca59187962:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    bcfc5b30c4634387a1cdead584693ef8:
      title: The Five Wisdoms
      parent: Dzogchen
    680ba4612c324ec78e8fed9c88623414:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    08a06a0e417b45a4b8edd74868534a58:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    e599795c093647fdb689b5b3d80ada8c:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    b3fa4190d2f64535a1aab1f727af74d5:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    3a92e93d3c454abb8fc7845ef53593c2:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    d4f956b195a84253b6cad411b49d878a:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.760142'
last_modified_at: '2022-03-01T00:22:24.760146'
